In [20]:
import numpy as np


In [2]:
a=np.array([1,2,3])

In [3]:
a

array([1, 2, 3])

In [4]:
c=np.array([(1,2,3),(4,5,6)])

In [5]:
print(c)

[[1 2 3]
 [4 5 6]]


In [7]:
trans=np.transpose(c)

In [8]:
print(trans)

[[1 4]
 [2 5]
 [3 6]]


In [13]:
jack.rawel()

NameError: name 'jack' is not defined

In [14]:
a.reshape(3,1)

array([[1],
       [2],
       [3]])

In [20]:
vicky.rawel()

NameError: name 'vicky' is not defined

In [18]:
a.reshape(1,3)

array([[1, 2, 3]])

In [21]:
ze=np.zeros((3,3))

In [23]:
print(ze)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [24]:
one=np.ones((3,3))

In [25]:
print(one)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
